<?php
declare(strict_types=1);
$projects = require __DIR__ . '/config/projects.php';
$lang = ($_GET['lang'] ?? 'id') === 'en' ? 'en' : 'id';
$t = [
'id' => ['title'=>'Commercial & Licensing','eyebrow'=>'COMMERCIAL','headline'=>'Turn a proven system into your deployment.','copy'=>'Software dapat dilisensikan, dikustomisasi, diintegrasikan, dan dikembangkan sesuai kebutuhan organisasi.','model'=>'Model kerja','items'=>[['title'=>'License','text'=>'Hak penggunaan software untuk lingkungan dan jumlah deployment yang disepakati.'],['title'=>'Customization','text'=>'Penyesuaian UI, workflow, business rules, dan integrasi.'],['title'=>'Integration','text'=>'Koneksi dengan SIMRS, API, database, perangkat, atau sistem lain.'],['title'=>'Development','text'=>'Pengembangan fitur baru dan dukungan roadmap produk.']],'cta'=>'Diskusikan Kebutuhan','back'=>'← Kembali ke portfolio'],
'en'=>['title'=>'Commercial & Licensing','eyebrow'=>'COMMERCIAL','headline'=>'Turn a proven system into your deployment.','copy'=>'Software can be licensed, customized, integrated, and further developed for your organization.','model'=>'Engagement model','items'=>[['title'=>'License','text'=>'Usage rights for agreed environments and deployment scope.'],['title'=>'Customization','text'=>'UI, workflow, business rules, and integration adjustments.'],['title'=>'Integration','text'=>'Connect with SIMRS, APIs, databases, devices, or other systems.'],['title'=>'Development','text'=>'New features and ongoing product roadmap development.']],'cta'=>'Discuss Your Needs','back'=>'← Back to portfolio']]
][$lang];
?>
<!doctype html><html lang="<?= $lang ?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="<?= htmlspecialchars($t['title']) ?> — BLACKMEVALLY"><title><?= htmlspecialchars($t['title']) ?> — BLACKMEVALLY</title><link rel="stylesheet" href="assets/css/style.css"></head><body>
<header class="site-header"><div class="container nav-wrap"><a class="brand" href="index.php?lang=<?= $lang ?>">BLACKMEVALLY</a><nav><a href="index.php?lang=<?= $lang ?>#products"><?= $lang==='id'?'Products':'Products' ?></a><a href="commercial.php?lang=<?= $lang ?>"><?= $t['title'] ?></a><a href="contact.php?lang=<?= $lang ?>">Contact</a><span class="lang-switch"><a href="?lang=id" class="<?= $lang==='id'?'active':'' ?>">ID</a><a href="?lang=en" class="<?= $lang==='en'?'active':'' ?>">EN</a></span></nav></div></header>
<main><section class="commercial-hero section"><div class="container narrow"><span class="eyebrow"><?= $t['eyebrow'] ?></span><h1><?= htmlspecialchars($t['headline']) ?></h1><p class="hero-copy"><?= htmlspecialchars($t['copy']) ?></p></div></section>
<section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">OPTIONS</span><h2><?= htmlspecialchars($t['model']) ?></h2></div></div><div class="solution-grid commercial-grid"><?php foreach($t['items'] as $item): ?><article class="solution"><span class="card-index">0<?= array_search($item,$t['items'],true)+1 ?></span><h3><?= htmlspecialchars($item['title']) ?></h3><p><?= htmlspecialchars($item['text']) ?></p></article><?php endforeach; ?></div></div></section>
<section class="cta-section"><div class="container cta-inner"><div><span class="eyebrow">NEXT STEP</span><h2><?= htmlspecialchars($t['cta']) ?></h2></div><a class="btn btn-primary" href="contact.php?lang=<?= $lang ?>"><?= htmlspecialchars($t['cta']) ?> →</a></div></section></main><footer class="site-footer"><div class="container"><span>© <?= date('Y') ?> BLACKMEVALLY</span><a href="index.php?lang=<?= $lang ?>"><?= htmlspecialchars($t['back']) ?></a></div></footer></body></html>
