<?php
declare(strict_types=1);
$lang = ($_GET['lang'] ?? 'id') === 'en' ? 'en' : 'id';
$t = $lang==='id' ? ['eyebrow'=>'CONTACT','title'=>'Mari bicarakan sistem yang Anda butuhkan.','copy'=>'Ceritakan masalah, workflow, atau produk yang ingin di-deploy. Kami dapat membahas lisensi, demo, custom development, dan integrasi.','name'=>'Nama','org'=>'Organisasi / Perusahaan','email'=>'Email','product'=>'Produk yang diminati','message'=>'Kebutuhan / pesan','send'=>'Kirim melalui Email','commercial'=>'Commercial & Licensing','placeholder'=>'Jelaskan kebutuhan, target pengguna, dan integrasi yang diperlukan.'] : ['eyebrow'=>'CONTACT','title'=>'Let’s discuss the system you need.','copy'=>'Tell us about the problem, workflow, or product you want to deploy. We can discuss licensing, demos, custom development, and integration.','name'=>'Name','org'=>'Organization / Company','email'=>'Email','product'=>'Product of interest','message'=>'Requirements / message','send'=>'Send via Email','commercial'=>'Commercial & Licensing','placeholder'=>'Describe your needs, users, and required integrations.'];
$subject = rawurlencode(($lang==='id'?'Inquiry Portfolio — ':'Portfolio Inquiry — ').($_GET['product'] ?? 'General'));
?>
<!doctype html><html lang="<?= $lang ?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Contact BLACKMEVALLY"><title>Contact — BLACKMEVALLY</title><link rel="stylesheet" href="assets/css/style.css"></head><body>
<header class="site-header"><div class="container nav-wrap"><a class="brand" href="index.php?lang=<?= $lang ?>">BLACKMEVALLY</a><nav><a href="index.php?lang=<?= $lang ?>#products">Products</a><a href="commercial.php?lang=<?= $lang ?>"><?= htmlspecialchars($t['commercial']) ?></a><a href="contact.php?lang=<?= $lang ?>">Contact</a><span class="lang-switch"><a href="?lang=id" class="<?= $lang==='id'?'active':'' ?>">ID</a><a href="?lang=en" class="<?= $lang==='en'?'active':'' ?>">EN</a></span></nav></div></header>
<main><section class="section contact-hero"><div class="container contact-grid"><div><span class="eyebrow"><?= $t['eyebrow'] ?></span><h1><?= htmlspecialchars($t['title']) ?></h1><p class="hero-copy"><?= htmlspecialchars($t['copy']) ?></p></div><form class="contact-form" action="mailto:contact@blackmevally.dev" method="post" enctype="text/plain"><label><?= $t['name'] ?><input name="name" required></label><label><?= $t['org'] ?><input name="organization"></label><label><?= $t['email'] ?><input type="email" name="email" required></label><label><?= $t['product'] ?><input name="product" value="<?= htmlspecialchars($_GET['product'] ?? '') ?>"></label><label><?= $t['message'] ?><textarea name="message" rows="7" placeholder="<?= htmlspecialchars($t['placeholder']) ?>" required></textarea></label><a class="btn btn-primary" href="mailto:contact@blackmevally.dev?subject=<?= $subject ?>"><?= htmlspecialchars($t['send']) ?> →</a><small>contact@blackmevally.dev</small></form></div></section></main><footer class="site-footer"><div class="container"><span>© <?= date('Y') ?> BLACKMEVALLY</span><span><a href="commercial.php?lang=<?= $lang ?>"><?= htmlspecialchars($t['commercial']) ?></a></span></div></footer></body></html>
