<?php
declare(strict_types=1);
$projects = require __DIR__ . '/config/projects.php';
$lang = ($_GET['lang'] ?? 'id') === 'en' ? 'en' : 'id';
$slug = (string)($_GET['product'] ?? '');
$selected = null; foreach ($projects as $p) { if ($p['slug'] === $slug) { $selected = $p; break; } }
$product = $selected['title'] ?? '';
$t = $lang==='id' ? ['ey'=>'DEMO REQUEST','title'=>'Mari jadwalkan demo.','copy'=>'Pilih produk, jelaskan kebutuhan Anda, lalu kirim inquiry. Kami akan menggunakan detail ini sebagai brief awal untuk pembahasan demo, deployment, lisensi, atau customization.','name'=>'Nama','org'=>'Organisasi / Perusahaan','email'=>'Email','phone'=>'WhatsApp / Telepon','product'=>'Produk','scope'=>'Kebutuhan / scope','timeline'=>'Target implementasi','send'=>'Buka Email Inquiry','commercial'=>'Commercial & Licensing'] : ['ey'=>'DEMO REQUEST','title'=>'Let’s schedule a demo.','copy'=>'Choose a product, describe your needs, and send an inquiry. These details become the initial brief for a demo, deployment, licensing, or customization discussion.','name'=>'Name','org'=>'Organization / Company','email'=>'Email','phone'=>'WhatsApp / Phone','product'=>'Product','scope'=>'Requirements / scope','timeline'=>'Target timeline','send'=>'Open Email Inquiry','commercial'=>'Commercial & Licensing'];
$subject = rawurlencode(($lang==='id'?'Demo Request — ':'Demo Request — ').($product ?: 'BLACKMEVALLY'));
$body = rawurlencode(($lang==='id'?'Nama: [isi]\nOrganisasi: [isi]\nEmail: [isi]\nWhatsApp/Telepon: [isi]\nProduk: '.($product ?: '[pilih]').'\nTarget implementasi: [isi]\nKebutuhan/scope: [jelaskan]':'Name: [fill]\nOrganization: [fill]\nEmail: [fill]\nWhatsApp/Phone: [fill]\nProduct: '.($product ?: '[select]').'\nTarget timeline: [fill]\nRequirements/scope: [describe]'));
?><!doctype html><html lang="<?=$lang?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Request a BLACKMEVALLY software demo."><meta property="og:title" content="Demo Request — BLACKMEVALLY"><meta property="og:description" content="Request a product demo, deployment, customization, or integration discussion."><meta property="og:type" content="website"><title><?=htmlspecialchars($t['title'])?> — BLACKMEVALLY</title><link rel="stylesheet" href="assets/css/style.css"></head><body><header class="site-header"><div class="container nav-wrap"><a class="brand" href="index.php?lang=<?=$lang?>">BLACKMEVALLY</a><nav><a href="index.php?lang=<?=$lang?>#products">Products</a><a href="commercial.php?lang=<?=$lang?>"><?=$t['commercial']?></a><a href="contact.php?lang=<?=$lang?>">Contact</a><span class="lang-switch"><a href="?lang=id&product=<?=urlencode($slug)?>">ID</a><a href="?lang=en&product=<?=urlencode($slug)?>">EN</a></span></nav></div></header><main><section class="section contact-hero"><div class="container contact-grid"><div><span class="eyebrow"><?=$t['ey']?></span><h1><?=htmlspecialchars($t['title'])?></h1><p class="hero-copy"><?=htmlspecialchars($t['copy'])?></p></div><form class="contact-form" onsubmit="return false"><label><?=$t['name']?><input required></label><label><?=$t['org']?><input></label><label><?=$t['email']?><input type="email" required></label><label><?=$t['phone']?><input></label><label><?=$t['product']?><input value="<?=htmlspecialchars($product)?>"></label><label><?=$t['timeline']?><input></label><label><?=$t['scope']?><textarea rows="6"></textarea></label><a class="btn btn-primary" href="mailto:contact@blackmevally.dev?subject=<?=$subject?>&body=<?=$body?>"><?=htmlspecialchars($t['send'])?> →</a><small>contact@blackmevally.dev</small></form></div></section></main><footer class="site-footer"><div class="container"><span>© <?=date('Y')?> BLACKMEVALLY</span><a href="commercial.php?lang=<?=$lang?>"><?=$t['commercial']?></a></div></footer></body></html>