<?php

declare(strict_types=1);

return [
    [
        'slug' => 'antrian-pendaftaran',
        'title' => 'Antrian Pendaftaran',
        'category' => 'Healthcare',
        'type' => 'Hospital Queue Management System',
        'status' => 'Production',
        'availability' => 'Commercial + Customization',
        'repo' => 'https://github.com/blackmevally/antrianpoli',
        'demo' => null,
        'summary' => 'Web-based queue display and calling workflow for outpatient registration and POLI operations.',
        'problem' => 'Help hospitals present and call patient queues clearly across registration and clinic displays.',
        'solution' => 'A lightweight PHP/MySQL display with realtime events, TTS announcements, POLI cards, and kiosk-friendly presentation.',
        'features' => ['Realtime queue updates', 'Text-to-speech calling', 'POLI-specific display', 'Kiosk-friendly UI', 'SIMRS database integration'],
        'stack' => ['PHP', 'MySQL', 'JavaScript', 'SSE', 'Web Speech'],
    ],
    [
        'slug' => 'antrian-farmasi',
        'title' => 'Antrian Farmasi',
        'category' => 'Healthcare',
        'type' => 'Pharmacy Queue Display',
        'status' => 'Production',
        'availability' => 'Commercial + Customization',
        'repo' => 'https://github.com/blackmevally/AntrianFarmasi',
        'demo' => null,
        'summary' => 'Queue calling display for pharmacy services with audio announcements and media integration.',
        'problem' => 'Pharmacy counters need a visible queue display while keeping announcements understandable in a busy environment.',
        'solution' => 'A browser-based queue display with TTS, notification audio, video fallback, and configurable service hours.',
        'features' => ['Queue calling', 'TTS audio', 'Video/stream fallback', 'Service-hours handling', 'Responsive display'],
        'stack' => ['PHP', 'JavaScript', 'MySQL', 'HLS', 'OBS/Nginx'],
    ],
    [
        'slug' => 'hospital-dashboard',
        'title' => 'Hospital Dashboard',
        'category' => 'Healthcare',
        'type' => 'Hospital Operations Dashboard',
        'status' => 'Development',
        'availability' => 'Commercial',
        'repo' => 'https://github.com/blackmevally/dashboard_ss',
        'demo' => null,
        'summary' => 'Operations-focused dashboard concept for presenting hospital data in a command-center style view.',
        'problem' => 'Operational data is often spread across systems and difficult to interpret at a glance.',
        'solution' => 'A centralized visual dashboard designed for TV walls, workstations, and command-center environments.',
        'features' => ['KPI cards', 'TV-ready layouts', 'Modular dashboard sections', 'Future API integrations'],
        'stack' => ['PHP', 'JavaScript', 'CSS', 'API integration'],
    ],
    [
        'slug' => 'satusehat-integration',
        'title' => 'SatuSehat Integration',
        'category' => 'Healthcare',
        'type' => 'Health Data Integration',
        'status' => 'Development',
        'availability' => 'Commercial + Customization',
        'repo' => null,
        'demo' => null,
        'summary' => 'Integration-oriented work for connecting hospital workflows to SatuSehat/FHIR services.',
        'problem' => 'Healthcare systems need practical bridges between local workflows and national interoperability services.',
        'solution' => 'Reusable integration components and validation tooling designed around FHIR-style healthcare data flows.',
        'features' => ['FHIR-oriented payloads', 'Patient/IHS workflows', 'Sandbox validation', 'Integration tooling'],
        'stack' => ['PHP', 'REST API', 'FHIR', 'JSON'],
    ],
    [
        'slug' => 'aplicare-monitoring',
        'title' => 'Aplicare Monitoring',
        'category' => 'Healthcare',
        'type' => 'Bed Availability Monitoring',
        'status' => 'Development',
        'availability' => 'Commercial + Customization',
        'repo' => null,
        'demo' => null,
        'summary' => 'Monitoring and synchronization workflow for hospital bed availability and Aplicare-related operational data.',
        'problem' => 'Bed availability information must remain visible, current, and easy to verify.',
        'solution' => 'Monitoring and push workflows that connect internal hospital data with external availability services.',
        'features' => ['Bed mapping', 'Availability monitoring', 'Push workflow', 'Operational dashboard'],
        'stack' => ['PHP', 'MySQL', 'REST API', 'Cron/automation'],
    ],
    [
        'slug' => 'orthanc-integration',
        'title' => 'Orthanc Integration',
        'category' => 'Healthcare',
        'type' => 'Medical Imaging Integration',
        'status' => 'Development',
        'availability' => 'Commercial + Customization',
        'repo' => null,
        'demo' => null,
        'summary' => 'Workflow tooling for synchronizing and monitoring DICOM/Orthanc data with hospital databases.',
        'problem' => 'Medical imaging systems and operational databases may need a dependable synchronization layer.',
        'solution' => 'Batch synchronization and monitoring workflows designed to bridge Orthanc with MySQL-based applications.',
        'features' => ['Orthanc synchronization', 'Batch processing', 'Date filtering', 'MySQL mirroring'],
        'stack' => ['PHP', 'Orthanc API', 'MySQL', 'DICOM'],
    ],
    [
        'slug' => 'simrs-integration',
        'title' => 'SIMRS Integration',
        'category' => 'Healthcare',
        'type' => 'Hospital Information System Extensions',
        'status' => 'Production / R&D',
        'availability' => 'Commercial + Customization',
        'repo' => 'https://github.com/blackmevally/SIMRS-RSPM',
        'demo' => null,
        'summary' => 'Extensions and integrations around SIMRS/Khanza workflows for operational use cases.',
        'problem' => 'Existing SIMRS platforms often need focused extensions without disrupting their core database and workflows.',
        'solution' => 'Small, targeted integration modules that work alongside existing SIMRS deployments.',
        'features' => ['Khanza integration', 'Database bridging', 'Operational modules', 'Deployment-focused tooling'],
        'stack' => ['PHP', 'MySQL/MariaDB', 'Java', 'Khanza'],
    ],
    [
        'slug' => 'masjid-digital',
        'title' => 'Masjid Digital',
        'category' => 'Community',
        'type' => 'Digital Mosque Information System',
        'status' => 'Active Development',
        'availability' => 'Commercial / Customization',
        'repo' => 'https://github.com/blackmevally/masjiddigital',
        'demo' => null,
        'summary' => 'Digital information and dashboard platform for mosque/community operations.',
        'problem' => 'Community organizations need simple digital tools for information, displays, and local operations.',
        'solution' => 'A lightweight web platform designed to run on inexpensive local hardware or a hosted server.',
        'features' => ['Digital display', 'Community information', 'TV/kiosk support', 'Local deployment'],
        'stack' => ['PHP', 'JavaScript', 'SQLite/MySQL'],
    ],
    [
        'slug' => 'parking-gate',
        'title' => 'Parking Gate System',
        'category' => 'Automation',
        'type' => 'Parking & Gate Automation',
        'status' => 'Experimental',
        'availability' => 'Commercial + Customization',
        'repo' => null,
        'demo' => null,
        'summary' => 'Automation concept for vehicle access, gate control, and operational logging.',
        'problem' => 'Small facilities need affordable automation that connects physical access devices with software.',
        'solution' => 'A modular software layer for gate events, identification, and logging with room for hardware integration.',
        'features' => ['Access event logging', 'Hardware integration path', 'Operator interface', 'Audit trail'],
        'stack' => ['PHP', 'JavaScript', 'MySQL', 'IoT/hardware'],
    ],
    [
        'slug' => 'face-recognition-attendance',
        'title' => 'Face Recognition Attendance',
        'category' => 'Automation',
        'type' => 'Attendance & Computer Vision',
        'status' => 'Experimental',
        'availability' => 'Commercial + Customization',
        'repo' => null,
        'demo' => null,
        'summary' => 'Attendance workflow concept using webcam-based face recognition and a MySQL-backed application.',
        'problem' => 'Attendance workflows can be improved by reducing manual input and connecting recognition to structured records.',
        'solution' => 'A web-facing attendance system concept with camera capture, recognition processing, and database storage.',
        'features' => ['Webcam capture', 'Recognition workflow', 'Attendance logs', 'MySQL integration'],
        'stack' => ['PHP', 'JavaScript', 'Webcam', 'MySQL', 'Computer Vision'],
    ],
];
